theme: jekyll-theme-minimal
title: "Ahmad Mheich"
logo: me.jpg
icons: sg_icon.png 
<p align="center"> <img src="https://komarev.com/ghpvc/?username=GITHUB-amheich&label=Profile%20views&color=ce9927&style=flat" alt="GITHUB-USERNAME" /> </p>
