theme: jekyll-theme-minimal
logo: images/me.jpg
title: "Abdallah Dib"
# Site Author
author:
  name             : "Ahmad Mheich"
  avatar           : "me.jpg" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Researcher at CCA-CHUV"
  location         : "Lausanne, Vaud"
  email            : "ahmad.mheich@chuv.ch"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "amheich"
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : # "li-zeng-154a2551?trk=nav_responsive_tab_profile_pic"
  pinterest        :
  soundcloud       :
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. http://stackoverflow.com/users/123456/username)
  steam            :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  xing             :
  youtube          :
