theme: jekyll-theme-minimal
logo: me.jpg
title: "Ahmad Mheich"
# Site Author
author:
  name             : "Ahmad Mheich"
  avatar           : "me.jpg" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Researcher at CCA-CHUV"
  location         : "Lausanne, Vaud"
  email            : "ahmad.mheich@chuv.ch"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "amheich"
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : 

